from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from .files import atomic_write_text
from .roles import DEFAULT_ROLES_ROOT, RolePolicy, RolePolicyError, load_all_role_policies

CODEXTEAM_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT_ROOT = CODEXTEAM_ROOT / "generated" / "native-agents"
GENERATED_MARKER = "# Generated by CodexTeam role-policy-v1. Do not edit."


def render_native_agent(policy: RolePolicy) -> str:
    fields = {
        "name": policy.name,
        "description": policy.description,
        "developer_instructions": policy.developer_instructions,
        "model_reasoning_effort": policy.default_reasoning_effort,
        "sandbox_mode": policy.sandbox_mode,
    }
    lines = [GENERATED_MARKER, f"# role_policy_digest = {policy.digest}"]
    lines.extend(f"{key} = {json.dumps(value)}" for key, value in fields.items())
    return "\n".join(lines) + "\n"


def expected_native_agents(
    *, roles_root: str | Path = DEFAULT_ROLES_ROOT
) -> dict[str, str]:
    return {
        f"{policy.name}.toml": render_native_agent(policy)
        for policy in load_all_role_policies(roles_root=roles_root)
    }


def sync_native_agents(
    destination: str | Path,
    *,
    roles_root: str | Path = DEFAULT_ROLES_ROOT,
    apply: bool = False,
) -> tuple[str, ...]:
    root = Path(destination).expanduser().resolve(strict=False)
    expected = expected_native_agents(roles_root=roles_root)
    changes: list[str] = []
    for name, content in expected.items():
        target = root / name
        if target.is_symlink():
            raise RolePolicyError(f"refusing to replace symlink: {target}")
        if target.exists():
            existing = target.read_text(encoding="utf-8")
            if existing == content:
                continue
            if not existing.startswith(GENERATED_MARKER):
                raise RolePolicyError(f"refusing to replace unmanaged native agent: {target}")
            action = "update"
        else:
            action = "create"
        changes.append(f"{action} {target}")
        if apply:
            root.mkdir(parents=True, exist_ok=True)
            atomic_write_text(target, content)
    return tuple(changes)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Check, generate, or install CodexTeam native custom-agent projections."
    )
    parser.add_argument(
        "--destination",
        help="Target directory; generated/native-agents by default, or $CODEX_HOME/agents with --install",
    )
    parser.add_argument("--roles-root", default=str(DEFAULT_ROLES_ROOT))
    parser.add_argument("--install", action="store_true", help="Target the active Codex agents directory")
    parser.add_argument("--apply", action="store_true", help="Write the reported changes")
    parser.add_argument("--check", action="store_true", help="Exit 1 when generated files are not current")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    if args.install and args.destination:
        print("ERROR: --install and --destination are mutually exclusive")
        return 2
    destination = args.destination
    if destination is None:
        destination = (
            Path(os.environ.get("CODEX_HOME", Path.home() / ".codex")) / "agents"
            if args.install
            else DEFAULT_OUTPUT_ROOT
        )
    try:
        changes = sync_native_agents(
            destination,
            roles_root=args.roles_root,
            apply=args.apply,
        )
    except (FileNotFoundError, OSError, RolePolicyError) as exc:
        print(f"ERROR: {exc}")
        return 2
    for change in changes:
        print(change)
    if not changes:
        print(f"Current: {Path(destination).expanduser().resolve(strict=False)}")
    elif not args.apply:
        print("Preview only; pass --apply to write changes.")
    if args.check and changes:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
