import tomllib
from pathlib import Path

import pytest

from codexteam_tools.native_agents import (
    DEFAULT_OUTPUT_ROOT,
    GENERATED_MARKER,
    expected_native_agents,
    sync_native_agents,
)
from codexteam_tools.roles import RolePolicyError


def test_native_agent_projection_is_valid_and_namespaced():
    generated = expected_native_agents()
    assert len(generated) == 9
    for name, content in generated.items():
        assert name.startswith("codexteam_")
        assert content.startswith(GENERATED_MARKER)
        parsed = tomllib.loads(content)
        assert parsed["name"] == name.removesuffix(".toml")
        assert parsed["developer_instructions"]
        assert "model_reasoning_effort" not in parsed


def test_native_agent_sync_previews_applies_and_becomes_current(tmp_path: Path):
    changes = sync_native_agents(tmp_path)
    assert len(changes) == 9
    assert list(tmp_path.iterdir()) == []

    assert len(sync_native_agents(tmp_path, apply=True)) == 9
    assert sync_native_agents(tmp_path) == ()


def test_native_agent_sync_refuses_unmanaged_overwrite(tmp_path: Path):
    target = tmp_path / "codexteam_developer.toml"
    target.write_text('name = "personal_agent"\n')
    with pytest.raises(RolePolicyError, match="unmanaged"):
        sync_native_agents(tmp_path, apply=True)


def test_checked_in_native_agent_projections_are_current():
    expected = expected_native_agents()
    actual = {
        path.name: path.read_text(encoding="utf-8")
        for path in sorted(DEFAULT_OUTPUT_ROOT.glob("*.toml"))
    }
    assert actual == expected


def test_native_agent_sync_upgrades_legacy_generated_marker(tmp_path: Path):
    target = tmp_path / "codexteam_developer.toml"
    target.write_text(
        "# Generated by CodexTeam role-policy. Do not edit.\n"
        'name = "codexteam_developer"\n',
        encoding="utf-8",
    )

    changes = sync_native_agents(tmp_path, apply=True)

    assert any(str(target) in change for change in changes)
    assert target.read_text(encoding="utf-8").startswith(GENERATED_MARKER)
